version: '3'

services:
  client:
    container_name: lectio-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    volumes:
      - './client/ssl:/client/etc/nginx/cert'

  server:
    container_name: lectio-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./server/certificates:/app/server/certificates
    expose:
      - '${SERVER_PORT}'